spring:
  main:
    allow-bean-definition-overriding: true
    # ??? ??? ?? ???
    #web-application-type: none


server:
  # port??
  port: 9090 # 0??? ???? ????? ??? ???
  # ??????
  #compression:
    #enabled: true

# auto configure test
holoman:
  name: holoman-properties-name1
  how-long: 122





